[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_contract = "GzcpjpMwSEYZKSi5ZupSfqTNaswBMxFhfESvXWbuURH1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Duc\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
